### PR TITLE
Add export to Drupal

### PR DESCRIPTION
**Pull request by amiller-ims**
Creates a file called body.html which is an extract of the rendered Respec document starting with the `<header>` element and finishing with the `<footer>` element. Any `<script>` elements found in that range are removed.

Should anything else be removed from that range?

Sample output (I changed the file name to .txt for GitHub comment, but let me know if you would prefer a different name):
[body.txt](https://github.com/IMSGlobal/respec/files/7355923/body.txt)

Export UI
image

### CODE REVIEW

**Comment by amiller-ims** [comment]
@bracken @mattpaz @mgylling - Would you take a look at this?

**Comment by mattpaz** [comment]
I'd suggest recasting it from `DRUPAL` to `CMS` (or something like that).  Looks like there were only 11 references to drupal in the code, so it shouldn't be bad.  If bracken and mgyling agree this is a benign addition that could have some upside potential down the road, I'd say everything else LGTM.

**Comment by amiller-ims** [comment]
Added command line capability:

```
node ./tools/respect2drupal --src spec.html --out drupal.txt
```

**Comment by amiller-ims** [comment]
> I'd suggest recasting it from `DRUPAL` to `CMS` (or something like that). Looks like there were only 11 references to drupal in the code, so it shouldn't be bad. If bracken and mgyling agree this is a benign addition that could have some upside potential down the road, I'd say everything else LGTM.

No, not hard. I'll change all references to CMS.

**Pull request merged**
